    private ThrowingRunnable evaluateWithException(final Exception exception) {
        return () -> {
            statement.nextException = exception;
            statement.waitDuration = 0;
            failOnTimeout.evaluate();
        };
    }
